Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 66, in <module>
    fi_train = open('data/' + args.prefix + '.train', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/digits_var10_1.train'
Traceback (most recent call last):
  File "model_trainer.py", line 66, in <module>
    fi_train = open('data/' + args.prefix + '.train', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/digits_var10_2.train'
Traceback (most recent call last):
  File "model_trainer.py", line 66, in <module>
    fi_train = open('data/' + args.prefix + '.train', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/digits_var10_3.train'
Traceback (most recent call last):
  File "model_trainer.py", line 66, in <module>
    fi_train = open('data/' + args.prefix + '.train', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/digits_var10_4.train'
Traceback (most recent call last):
  File "model_trainer.py", line 66, in <module>
    fi_train = open('data/' + args.prefix + '.train', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/digits_var10_5.train'
Traceback (most recent call last):
  File "model_trainer.py", line 66, in <module>
    fi_train = open('data/' + args.prefix + '.train', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/digits_var10_6.train'
Traceback (most recent call last):
  File "model_trainer.py", line 66, in <module>
    fi_train = open('data/' + args.prefix + '.train', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/digits_var10_7.train'
Traceback (most recent call last):
  File "model_trainer.py", line 66, in <module>
    fi_train = open('data/' + args.prefix + '.train', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/digits_var10_8.train'
Traceback (most recent call last):
  File "model_trainer.py", line 66, in <module>
    fi_train = open('data/' + args.prefix + '.train', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/digits_var10_9.train'
Traceback (most recent call last):
  File "model_trainer.py", line 66, in <module>
    fi_train = open('data/' + args.prefix + '.train', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/digits_var10_10.train'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 67, in <module>
    fi_dev = open('data/' + args.prefix + '.dev', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/digits_var6_1.dev'
Traceback (most recent call last):
  File "model_trainer.py", line 67, in <module>
    fi_dev = open('data/' + args.prefix + '.dev', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/digits_var6_2.dev'
Traceback (most recent call last):
  File "model_trainer.py", line 67, in <module>
    fi_dev = open('data/' + args.prefix + '.dev', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/digits_var6_3.dev'
Traceback (most recent call last):
  File "model_trainer.py", line 66, in <module>
    fi_train = open('data/' + args.prefix + '.train', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/digits_var6_4.train'
Traceback (most recent call last):
  File "model_trainer.py", line 66, in <module>
    fi_train = open('data/' + args.prefix + '.train', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/digits_var6_5.train'
Traceback (most recent call last):
  File "model_trainer.py", line 66, in <module>
    fi_train = open('data/' + args.prefix + '.train', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'data/digits_var6_6.train'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
Traceback (most recent call last):
  File "model_trainer.py", line 158, in <module>
    encoder.load_state_dict(torch.load("models/encoder_" + args.enc_file_prefix + ".weights", map_location=device))
  File "/software/apps/anaconda/5.2/python/3.6/envs/marcc-python3.6-pytorch0.4.1/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder_var10_withheld_rtl_ltr_ltr_auto_2.weights'
